"""Sequential action controller. Policy actions are data, never host shell commands."""
import os
from pathlib import Path
import tempfile
import time

from .experiment import ExperimentConfig
from .integrity import MAX_SOURCE_BYTES, submission_source
from .tasks import training_tasks, heldout_tasks
from .trajectory import Recorder


class Controller:
    def __init__(self, task, submission, log_path, config=None, backend=None, *, evaluation=False, remaining_actions=None,
                 resume_records=None, resume_sources=None):
        self.config = (config or ExperimentConfig()).validate()
        if task not in (heldout_tasks() if evaluation else training_tasks()):
            raise ValueError("Controller requires a canonical training task")
        self.submission = Path(submission).resolve()
        budget = self.config.max_actions if remaining_actions is None else remaining_actions
        if not 1 <= budget <= self.config.max_actions:
            raise ValueError("Invalid continuation budget")
        self.recorder = Recorder(task, self.submission, log_path, budget, backend, evaluation=evaluation,
                                 resume_records=resume_records, resume_sources=resume_sources)

    def step(self, action):
        started = time.monotonic()
        if self.recorder.stopped or len(self.recorder.records) >= self.recorder.max_actions:
            raise ValueError("Rollout budget exhausted or stopped")
        if not isinstance(action, dict) or set(action) - {"type", "source", "proposed_next_action"}:
            raise ValueError("Unsupported action fields")
        kind = action.get("type")
        if kind not in {"edit", "test", "stop"}:
            raise ValueError("Only edit, test and stop are enabled; profiling is excluded from this pilot")
        proposed = action.get("proposed_next_action", "")
        if not isinstance(proposed, str) or len(proposed) > 4096:
            raise ValueError("Invalid proposed next action")
        if kind == "edit":
            source = action.get("source")
            if not isinstance(source, str) or len(source.encode()) > MAX_SOURCE_BYTES:
                raise ValueError("Edit must supply candidate.py source within size limit")
            submission_source(self.submission)  # Reject symlinks, extra files, or changed layout.
            with tempfile.NamedTemporaryFile(mode="w", dir=self.submission, delete=False) as stream:
                temporary = Path(stream.name)
                stream.write(source)
            try:
                os.replace(temporary, self.submission / "candidate.py")
            finally:
                temporary.unlink(missing_ok=True)
        elif "source" in action:
            raise ValueError("Only edit actions may contain source")
        # Action signature is generated by the controller, not supplied by the model.
        record = self.recorder.record(kind, "edit candidate.py" if kind == "edit" else kind,
                                      proposed_next_action=proposed, wall_seconds=time.monotonic() - started,
                                      policy_action=dict(action))
        # This is the policy-facing boundary. Rich audit logs and training reward
        # remain trainer-only, never inserted into model context.
        return record["policy_observation"]

    def reject_action(self, reason=None):
        """Invalid model JSON/actions consume budget; no free retries."""
        record = self.recorder.record("invalid", "invalid_action", action_error=reason)
        return record["policy_observation"]


def run_script(task, submission, log_path, actions, config=None, backend=None):
    controller = Controller(task, submission, log_path, config, backend)
    for action in actions:
        controller.step(action)
        if controller.recorder.stopped or len(controller.recorder.records) >= controller.config.max_actions:
            break
    return controller.recorder.records
