"""Atomic collection state and reconstruction of interrupted frozen-policy rollouts."""
from dataclasses import asdict
import hashlib
import json
import os
from pathlib import Path
import uuid


def atomic_json(path, payload):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(path.name + '.' + uuid.uuid4().hex + '.tmp')
    with temporary.open('w') as stream:
        json.dump(payload, stream, indent=2, allow_nan=False)
        stream.flush()
        os.fsync(stream.fileno())
    os.replace(temporary, path)


def read_jsonl(path, repair=False):
    path = Path(path)
    if not path.exists():
        return []
    lines = path.read_text().splitlines(keepends=True)
    result = []
    for i, line in enumerate(lines):
        try:
            result.append(json.loads(line))
        except json.JSONDecodeError:
            if not repair or i != len(lines) - 1:
                raise
            path.with_name(path.name + '.interrupted-' + uuid.uuid4().hex).write_text(''.join(lines))
            path.write_text(''.join(json.dumps(row) + '\n' for row in result))
    return [load_details(path.parent, row) for row in result]


def load_details(directory, row):
    if "details_file" not in row:
        return row
    directory = Path(directory).resolve()
    path = (directory / row['details_file']).resolve()
    if not path.is_relative_to(directory):
        raise ValueError('Log detail path escapes rollout directory')
    return json.loads(path.read_text())


def unpack_step(row):
    from .policy import Completion
    from .rollouts import Snapshot
    return {'snapshot': Snapshot(row['source'], row['history'], row['remaining']),
            'completion': Completion(row['prompt'], row['completion'], row['prompt_ids'], row['output_ids']),
            'value_advantage': row.get('value_advantage', 0.0), 'wall_seconds': row.get('wall_seconds', 0.0)}


def completed_rollout(directory):
    directory = Path(directory)
    path = directory / 'trajectory.json'
    if not path.exists():
        return None
    result = json.loads(path.read_text())
    result['steps'] = [unpack_step(load_details(directory, row)) for row in result['steps']]
    result['records'] = read_jsonl(directory / 'protected.jsonl')
    if not result['records'] or not result['records'][-1]['done']:
        raise ValueError(f'Incomplete trajectory marked complete: {directory}')
    result['submission'] = str(directory / 'submission')
    return result


def recover_partial(directory, initial):
    from .policy import Completion
    from .rollouts import Snapshot
    directory = Path(directory)
    records = read_jsonl(directory / 'protected.jsonl', repair=True)
    completions = {r['index']: r for r in read_jsonl(directory / 'completions.jsonl', repair=True)}
    source, history, steps = initial.source, list(initial.history), []
    for i, record in enumerate(records):
        if record['index'] != i or i not in completions:
            raise ValueError(f'Missing persisted completion for action {i} in {directory}')
        raw = completions[i]
        if "snapshot" in raw:
            saved = raw["snapshot"]
            if saved["source"] != source or saved["remaining"] != initial.remaining - i:
                raise ValueError(f'Resume snapshot mismatch at action {i} in {directory}')
            history = list(saved['history'])
        completion = Completion(raw['prompt'], raw['completion'], raw['prompt_ids'], raw['output_ids'])
        if hashlib.sha256(source.encode()).hexdigest() != record['checkpoint']['before_hash']:
            raise ValueError(f'Resume source mismatch before action {i} in {directory}')
        steps.append({'snapshot': Snapshot(source, list(history), initial.remaining - i),
                      'completion': completion, 'value_advantage': 0.0,
                      'wall_seconds': raw.get('wall_seconds', 0.0)})
        action = record.get('policy_action')
        if record['checkpoint']['action'] == 'edit':
            source = action['source']
        if hashlib.sha256(source.encode()).hexdigest() != record['checkpoint']['after_hash']:
            raise ValueError(f'Resume source mismatch after action {i} in {directory}')
        history.extend([{'role': 'assistant', 'content': completion.text},
                        {'role': 'user', 'content': json.dumps(record['policy_observation'], sort_keys=True)}])
    # An edit may have reached disk before its record was committed. Roll it back
    # to the last committed action; the unfinished action is regenerated by seed.
    (directory / 'submission' / 'candidate.py').write_text(source)
    return records, steps, source, history
